### ISSUE TITLE
run python dreamer/dream.py --track columbia --obs_type lidar   ERROR

### ISSUE THREAD

**Issue by lmc19970711** [CPS-TUWien/racing_dreamer#2]
Traceback (most recent call last):
  File "dreamer/dream.py", line 15, in <module>
    import wrappers as wrappers
  File "/home/lmc/PycharmProjects/racing_dreamer/dreamer/wrappers.py", line 5, in <module>
    from racecar_gym.envs.multi_agent_race import MultiAgentScenario, MultiAgentRaceEnv
  File "/home/lmc/PycharmProjects/racing_dreamer/dreamer/src/racecar-gym/racecar_gym/__init__.py", line 27, in <module>
    _register_multi_agent(name=f'MultiAgent{name}-v0', file=scenario_file, rendering=False)
  File "/home/lmc/PycharmProjects/racing_dreamer/dreamer/src/racecar-gym/racecar_gym/__init__.py", line 9, in _register_multi_agent
    scenario = MultiAgentScenario.from_spec(path=f'{base_path}/../scenarios/{file}', rendering=rendering)
  File "/home/lmc/PycharmProjects/racing_dreamer/dreamer/src/racecar-gym/racecar_gym/envs/scenarios.py", line 30, in from_spec
    return MultiAgentScenario(world=load_world(spec.world, agents=list(agents.values())), agents=agents)
  File "/home/lmc/PycharmProjects/racing_dreamer/dreamer/src/racecar-gym/racecar_gym/bullet/providers.py", line 84, in load_world
    raise NotImplementedError(f'No scene with name {spec.name} implemented.')
NotImplementedError: No scene with name plechaty implemented.
How to solve this error?

**Comment by Vishal1711** [comment]
What is training time if I run dream.py? I am new to RL, not getting a clear idea about training time for dreamer.
