### ISSUE TITLE
Device kernel image invalid

### ISSUE THREAD

**Issue by Vishal1711** [CPS-TUWien/racing_dreamer#7]
I build a dreamer image and named it nodedreamer and try to run `dream.py` inside that. (Psb)
It showed error like `tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: device kernel image is invalid`. Is this related to Dockerfile inside the dreamer directory?

```
df@u20:~/2D_Racing/racing_dreamer/dreamer$ docker run -u $(id -u):$(id -g) -v $(pwd):/src --gpus all --rm nodedreamer python dream.py --track columbia --steps 10000
2021-12-07 08:21:21.062542: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-kpidwa0v because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
pybullet build time: Dec  1 2021 18:32:25
2021-12-07 08:21:29.433985: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-12-07 08:21:29.458204: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:68:00.0 name: NVIDIA RTX A6000 computeCapability: 8.6
coreClock: 1.8GHz coreCount: 84 deviceMemorySize: 47.54GiB deviceMemoryBandwidth: 715.34GiB/s
2021-12-07 08:21:29.458230: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-12-07 08:21:29.460176: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-12-07 08:21:29.461682: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-12-07 08:21:29.462002: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-12-07 08:21:29.463908: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-12-07 08:21:29.464991: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-12-07 08:21:29.468669: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-12-07 08:21:29.469044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-12-07 08:21:29.474093: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-07 08:21:29.498821: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3299990000 Hz
2021-12-07 08:21:29.501290: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4a4bab0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-12-07 08:21:29.501326: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-12-07 08:21:29.591144: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x47d8350 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-12-07 08:21:29.591196: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA RTX A6000, Compute Capability 8.6
2021-12-07 08:21:29.591855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:68:00.0 name: NVIDIA RTX A6000 computeCapability: 8.6
coreClock: 1.8GHz coreCount: 84 deviceMemorySize: 47.54GiB deviceMemoryBandwidth: 715.34GiB/s
2021-12-07 08:21:29.591909: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-12-07 08:21:29.591998: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-12-07 08:21:29.592047: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-12-07 08:21:29.592078: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-12-07 08:21:29.592118: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-12-07 08:21:29.592158: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-12-07 08:21:29.592199: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-12-07 08:21:29.592890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-12-07 08:21:29.592949: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "dream.py", line 274, in <module>
    main(args)
  File "dream.py", line 191, in main
    writer = tf.summary.create_file_writer(str(config.logdir), max_queue=1000, flush_millis=20000)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/summary_ops_v2.py", line 385, in create_file_writer_v2
    with ops.name_scope(name, "create_file_writer") as scope, ops.device("cpu:0"):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 5223, in device
    return context.device(device_name_or_function)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 2036, in device
    ensure_initialized()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 1833, in ensure_initialized
    context().ensure_initialized()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 539, in ensure_initialized
    context_handle = pywrap_tfe.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: device kernel image is invalid
```

**Comment by axelbr** [comment]
I can not reproduce this error. However, we only work with GeForce GPU's. This seems to be an issue with your hardware. My guess is that you maybe need another base image for Quadro GPU's with a different set of compiled CUDA drivers. But I am not certain about this.
